version: '3.7'

networks:
  catalog:
    driver: ${NETWORKS_DRIVER}

services:
  mongo:
    image: catalog/mongo
    container_name: mongo
    build:
      context: .
      dockerfile: ./mongo/Dockerfile
      args:
        MONGO_VERSION: ${MONGO_VERSION}
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - "${SERVICE_DIR}/mongo/data/db:/data/db"
      - "${SERVICE_DIR}/mongo/init:/docker-entrypoint-initdb.d:ro"
    ports:
      - "2000:${MONGO_PORT}"
    networks:
      - catalog

  catalog:
    image: catalog/catalog
    container_name: catalog
    build:
      context: ../
      dockerfile: ./.docker/catalog/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        WORK_DIR: ${WORK_DIR}
    environment:
      - MONGO_PORT=${MONGO_PORT}
    volumes:
      - '${BASE_DIR}:${WORK_DIR}'
    ports:
      - '${CATALOG_PORT}:${CATALOG_PORT}'
    networks:
      - catalog